language: node_js
node_js:
- 7
install:
- npm install
script:
- npm run lint
- npm run unit-test
- docker-compose -f docker-compose.yml run test npm run integration-test
deploy:
  provider: heroku
  api_key:
    secure: EWHhA2q4KwNW+Kwr9ommp/yD1hwROQzbL3M5dcuUGR8EnFPlPLX5/jXwkOsyEJ8vqMFynpXwWwKR4iRVVPdKvJuImQnpKYRqN8TES7nrzTkXlKc8V9xyD8rRlrtrmF/uGUbiEpjVpxAV2g5NBbBaXxVZTbH3kVas/hsZZI5H/Cs+JF68cO+rFqbp2XEQmQOggNJ5YCmFsZpB7VEjxLuqULc2/EiReidVLZv/Rc43a31CjS9gNCDxlPc1LhGZI3DXs28PhHxAvw8/nrhFwiFU+CNJw5haIzmGBUobuEGch52P3Bljs/LnXVgDOXD0aH1EoEpBcUq2bJ+NB832Qyb+8wpxhin+7RFjVpyJxd8J9WQBt8m7ybIvG2nBjw51nxP5wAfPTJH+EV1BT1l+kuvAt4T5IlJGTvOxWOpmZXbghb6krtf64gPrG+t2srytl06izQsbweWrjggglicdqLrBGEbbFke8Yf/B04b8K7BxIhHVEA6/66XBQPBi+vnqkHFL2iOviJniDOM02zXnuBaN+ZTKaH5AZP8rXttI42g3ak2bN5tw4KhdGjvAcjV+Yazm6O20r9qYxcSQ2PlkNIHeGuAAsXFdejyQ1p1QlRMwLPdZpKVYPHC2jaeJ0MSvcU+ybeORYajUKFbBIZYFpeSktw9WiDYWsrUTjqxlqe+sabc=
  app: vast-hamlet-12261
  on:
    repo: VamosJuntas/vamosjuntas-api
