version: "2"

services:
  test:
    build:
      dockerfile: infrastructure/docker/Dockerfile_nodejs_dev
      context: .
    volumes:
      - ./:/usr/app
    links:
      - db
    environment:
      - VAMOSJUNTAS_DATABASE_URL=mongodb://db/vamosjuntas
    command: [ npm, test ]

  db:
    build:
      dockerfile: infrastructure/docker/Dockerfile_mongodb_dev
      context: .
